//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public int PetId { get; set; }
        public string Name { get; set; }
        public double Weight { get; set; }
        public System.DateTime Birthday { get; set; }
        public int OwnerID { get; set; }
        public Nullable<bool> Gender { get; set; }
    
        public virtual Diet Diet { get; set; }
        public virtual User User { get; set; }
    }
}
